name: CI
on: [push]

jobs:
  blacken:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install black
      run: pip install black
    - name: Check formatting
      run: black --check --diff .

  test-dev:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install package
      run: pip install -e .[dev]
    - name: Run tests
      run: pytest -v

  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install package
      run: pip install .[dev]
    - name: Run tests
      run: pytest -v
